services:
  - type: web
    name: checkmate3
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_preprocess.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
